services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beats19182
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/beats19182
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-secret-key-here
      - ADMIN_EMAIL=example@example.com
      - ADMIN_PASSWORD=example
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

volumes:
  postgres_data:
  uploads: 